services:
  app:
    build: .
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    volumes:
      - .:/app
      - ${DATA_DIR:-./data}:/app/data
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    depends_on:
      - neo4j
    networks:
      - ${NETWORK_NAME:-dob-sob-network}
    deploy:
      resources:
        limits:
          memory: ${APP_MEMORY_LIMIT:-4G}
          cpus: "${APP_CPU_LIMIT:-2.0}"
        reservations:
          memory: ${APP_MEMORY_RESERVATION:-2G}
          cpus: "${APP_CPU_RESERVATION:-1.0}"
    restart: ${RESTART_POLICY:-unless-stopped}
    command: ["streamlit", "run", "main.py", "--server.address", "0.0.0.0"]

  neo4j:
    image: neo4j:5.26.7-community
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474" # HTTP
      - "${NEO4J_BOLT_PORT:-7687}:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G

    deploy:
      resources:
        limits:
          memory: ${NEO4J_MEMORY_LIMIT:-2G}
          cpus: "${NEO4J_CPU_LIMIT:-2.0}"
        reservations:
          memory: ${NEO4J_MEMORY_RESERVATION:-1G}
          cpus: "${NEO4J_CPU_RESERVATION:-1.0}"
    networks:
      - ${NETWORK_NAME:-dob-sob-network}
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER:-neo4j}", "-p", "${NEO4J_PASSWORD:-password}", "RETURN 1"]
      interval: ${HEALTH_CHECK_INTERVAL:-10s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-5s}
      retries: ${HEALTH_CHECK_RETRIES:-5}
      start_period: ${HEALTH_CHECK_START_PERIOD:-30s}

  jupyter:
    build: .
    ports:
      - "${JUPYTER_PORT:-8889}:8888"
    volumes:
      - .:/app
      - ${DATA_DIR:-./data}:/app/data
      - ${NOTEBOOKS_DIR:-./notebooks}:/app/notebooks
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    depends_on:
      - neo4j
    networks:
      - ${NETWORK_NAME:-dob-sob-network}
    deploy:
      resources:
        limits:
          memory: ${JUPYTER_MEMORY_LIMIT:-4G}
          cpus: "${JUPYTER_CPU_LIMIT:-2.0}"
        reservations:
          memory: ${JUPYTER_MEMORY_RESERVATION:-2G}
          cpus: "${JUPYTER_CPU_RESERVATION:-1.0}"
    restart: ${RESTART_POLICY:-unless-stopped}
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  dob-sob-network:
    name: ${NETWORK_NAME:-dob-sob-network}
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${NETWORK_MTU:-1450}
