# Production environment configuration

debug: false
environment: "production"

# Logging configuration
logging:
  level: "INFO"
  enable_file_logging: true
  log_file: "/var/log/dob_sob/dob_sob.log"
  max_file_size_mb: 50
  backup_count: 10

# API settings for production
api:
  requests_per_second: 10
  max_concurrent_downloads: 8
  timeout_seconds: 30

# Database settings (use environment variables in production)
database:
  uri: "${NEO4J_URI}"
  user: "${NEO4J_USER}"
  password: "${NEO4J_PASSWORD}"

# Web interface settings
web:
  streamlit_port: 8501
  jupyter_port: 8889
  api_port: 8000

# Fraud detection settings
fraud_detection:
  min_community_size: 5
  max_communities: 200
  high_risk_threshold: 0.8
  medium_risk_threshold: 0.5
  default_algorithms:
    - "louvain"
    - "label_propagation"
    - "edge_betweenness"
    - "spectral_clustering"